// <auto-generated />
using HouseService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HouseService.Migrations
{
    [DbContext(typeof(HouseDbContext))]
    [Migration("20250922084026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HouseService.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HouseId"));

                    b.Property<double>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("HouseId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            HouseId = 1,
                            Area = 250.5,
                            Name = "Modern Villa"
                        },
                        new
                        {
                            HouseId = 2,
                            Area = 85.0,
                            Name = "Cozy Apartment"
                        },
                        new
                        {
                            HouseId = 3,
                            Area = 180.69999999999999,
                            Name = "Family Home"
                        });
                });

            modelBuilder.Entity("HouseService.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoomId"));

                    b.Property<double>("Area")
                        .HasPrecision(10, 2)
                        .HasColumnType("double precision");

                    b.Property<int>("HouseId")
                        .HasColumnType("integer");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("RoomId");

                    b.HasIndex("HouseId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Area = 25.5,
                            HouseId = 1,
                            Placement = "Ground Floor"
                        },
                        new
                        {
                            RoomId = 2,
                            Area = 30.0,
                            HouseId = 1,
                            Placement = "First Floor"
                        },
                        new
                        {
                            RoomId = 3,
                            Area = 15.5,
                            HouseId = 2,
                            Placement = "Main Level"
                        },
                        new
                        {
                            RoomId = 4,
                            Area = 20.699999999999999,
                            HouseId = 3,
                            Placement = "Second Floor"
                        });
                });

            modelBuilder.Entity("HouseService.Room", b =>
                {
                    b.HasOne("HouseService.House", null)
                        .WithMany()
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
