version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: temperature-postgres
    environment:
      POSTGRES_DB: temperaturedb
      POSTGRES_USER: tempuser
      POSTGRES_PASSWORD: temppass123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - temperature-network

  house-postgres:
    image: postgres:15
    container_name: house-postgres
    environment:
      POSTGRES_DB: housedb
      POSTGRES_USER: houseuser
      POSTGRES_PASSWORD: housepass123
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - house_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - house-network

  temperature-service:
    build:
      context: .
      dockerfile: ./TemperatureService/Dockerfile
    container_name: temperature-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=temperaturedb;Username=tempuser;Password=temppass123;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
    ports:
      - "5002:80"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - temperature-network
      - messaging-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: house-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - messaging-network

  house-service:
    build:
      context: .
      dockerfile: ./HouseService/Dockerfile
    container_name: house-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTPS_PORT=
      - ASPNETCORE_Kestrel__Certificates__Default__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ConnectionStrings__DefaultConnection=Host=house-postgres;Port=5432;Database=housedb;Username=houseuser;Password=housepass123;
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
    ports:
      - "5001:80"
    depends_on:
      - house-postgres
      - rabbitmq
    networks:
      - house-network
      - messaging-network
    restart: unless-stopped

volumes:
  postgres_data:
  house_postgres_data:
  rabbitmq_data:

networks:
  temperature-network:
    driver: bridge
  house-network:
    driver: bridge
  messaging-network:
    driver: bridge
