using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using HouseService.Services;
using HouseService.Data;
using HouseService.Models;

namespace HouseService.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class HouseController : ControllerBase
    {
        private readonly HouseDbContext _context;
        private readonly ILogger<HouseController> _logger;
        private readonly IMessagePublisher _messagePublisher;

        public HouseController(HouseDbContext context, ILogger<HouseController> logger, IMessagePublisher messagePublisher)
        {
            _context = context;
            _logger = logger;
            _messagePublisher = messagePublisher;
        }

        [HttpGet]
        public async Task<ActionResult<IEnumerable<House>>> GetHouses()
        {
            return Ok(await _context.Houses.ToListAsync());
        }

        [HttpGet("{id}")]
        public async Task<ActionResult<House>> GetHouse(int id)
        {
            var house = await _context.Houses.FindAsync(id);
            if (house == null)
            {
                return NotFound();
            }
            return Ok(house);
        }

        [HttpPost]
        public async Task<ActionResult<House>> CreateHouse(CreateHouseRequest request)
        {
            if (request == null)
            {
                return BadRequest();
            }

            var house = new House
            {
                Name = request.Name,
                Address = request.Address,
                Area = request.Area
                // HouseId will be auto-generated by the database
            };
            
            _context.Houses.Add(house);
            await _context.SaveChangesAsync();
            
            // Publish HouseCreated event
            await _messagePublisher.PublishHouseCreatedAsync(house.HouseId, house.Name, house.Address, house.Area);
            
            return CreatedAtAction(nameof(GetHouse), new { id = house.HouseId }, house);
        }

        [HttpPut("{id}")]
        public async Task<IActionResult> UpdateHouse(int id, UpdateHouseRequest request)
        {
            if (request == null)
            {
                return BadRequest();
            }

            var house = await _context.Houses.FindAsync(id);
            if (house == null)
            {
                return NotFound();
            }

            // Update the house properties from the request
            house.Name = request.Name;
            house.Address = request.Address;
            house.Area = request.Area;

            _context.Entry(house).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
                
                // Publish HouseUpdated event
                await _messagePublisher.PublishHouseUpdatedAsync(house.HouseId, house.Name, house.Address, house.Area);
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!await HouseExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            
            return NoContent();
        }

        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteHouse(int id)
        {
            var house = await _context.Houses.FindAsync(id);
            if (house == null)
            {
                return NotFound();
            }

            _context.Houses.Remove(house);
            await _context.SaveChangesAsync();
            
            // Publish HouseDeleted event
            await _messagePublisher.PublishHouseDeletedAsync(id);
            
            return NoContent();
        }

        private async Task<bool> HouseExists(int id)
        {
            return await _context.Houses.AnyAsync(e => e.HouseId == id);
        }
    }
}